var pageAction=ZOLO.pageAction();var isListingPage=ZOLO.isListingPage();var search_url;function checkIfDrawerIsOpen(elem,drawerName){var isOpen;if($(elem).hasClass('drawer-open')){isOpen=true;ZOLO.whichSearchDrawer=drawerName;}else{isOpen=false;ZOLO.whichSearchDrawer='';}
return isOpen;}
$('.drawer-location-toggle').on('click',function(){checkIfDrawerIsOpen('#drawer-location','location-only');});$('.drawer-location-close').on('click',function(){checkIfDrawerIsOpen('#drawer-location');});$('.drawer-filters-toggle').on('click',function(){checkIfDrawerIsOpen('#drawer-filters','filters');});$('.drawer-filters-close').on('click',function(){checkIfDrawerIsOpen('#drawer-filters');});function updateZoloSearchLocation(data){var searchCity=ZOLO.searchCity();var searchNeighborhood=ZOLO.searchNeighborhood();if(data){var newCity=data.searchCity;var newNeighborhood=data.searchNeighborhood;}else{var newCity=$('.js-search-city').text();var newNeighborhood=$('.js-search-neighborhood').text();}
if(newCity!=searchCity){ZOLO_DATA.searchCity=newCity;}
if(newNeighborhood!=searchNeighborhood){ZOLO_DATA.searchNeighborhood=newNeighborhood;}}
function process_home_search(eventData){if($(window).width()>768){if(typeof pageAction!=='undefined'&&pageAction=='map'){updateZoloSearchLocation();set_search_url();reloadProperties();}else{$("#listing_container").addClass("loading").removeClass("transition-after-load");var url=tld+'ajax_listing_container.php';var eventDataPassed=false;if(eventData){eventDataPassed=true;}
var sdata=$("#home_search_top").serialize();$.ajax({type:"POST",url:url,data:sdata,success:function(data){if(eventDataPassed){$("#listing_container").html(eventData);}else{$("#listing_container").html(data);updateZoloSearchLocation();set_search_url(data);}
setTimeout(function(){$("#listing_container").removeClass("loading");$('#gallery').find('.image').lazyLoadXT();},150);}});}}else{if(typeof pageAction!=='undefined'&&pageAction=='map'||pageAction=='index'){$(".drawer-header-value-refresh").show();var url=tld+'ajax_listing_number.php';var sdata=$("#home_search_top").serialize();$.ajax({type:"POST",url:url,data:sdata,success:function(data){updateZoloSearchLocation(data);set_search_url();$("#listings_results").html(data.listingResults);$(".drawer-header-value-refresh").hide();}});}else if(typeof pageAction!=='undefined'&&isListingPage){var url=tld+'ajax_property_location_search.php';var sdata=$("#home_search_top").serialize();$.ajax({type:"POST",url:url,data:sdata,success:function(data){updateZoloSearchLocation(data)
set_search_url();}});}}}
function set_search_order(search_order){$('#search_order').val(search_order);$('#most_recent').removeClass('active');$('#most_expensive').removeClass('active');$('#least_expensive').removeClass('active');if(search_order==3){$('#most_recent').addClass('active');}
if(search_order==1){$('#most_expensive').addClass('active');}
if(search_order==2){$('#least_expensive').addClass('active');}
process_home_search();}
function set_min_prices(){var s_r=$("#s_r").val();var choices='';if(s_r==2){choices='<li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="0">0</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="600">$700+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="800">$900+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="1000">$1000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="1250">$1000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="1500">$2000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="2000">$2000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="2500">$2500+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="3000">$3000+</a></li>';}else{choices='<li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="0">0</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="200000">$200,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="300000">$300,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="400000">$400,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="600000">$600,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="800000">$800,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="1000000">$1,000,000+</a></li><li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-left" data-value="1500000">$1,500,000+</a></li>';}
$(".filter-price-min").html(choices);$('.filter-price-min a').on('click',function(e){e.preventDefault();$(".filter-price-min  a").removeClass("selected");$(this).addClass('selected');$('#price-min').val($(this).data('value'));if($(this).data('value')==0){$('#price-min').val('');}
var this_min_price=$(this).data('value');var current_max_filter=this_min_price;set_max_prices(current_max_filter)
var price_desc=change_price_desc($(this).data('value'),$('#price-max').val())
$("#price_desc").html(price_desc);$(".filter-price-min").hide();$(".filter-price-max").show();update_search_nav();process_home_search();$("#price-filter").addClass('open');$("#price-max").focus();});}
function set_max_prices(current_max_filter){if(current_max_filter==null){current_max_filter=0;}
if(current_max_filter==''){current_max_filter=0;}
var s_r=$("#s_r").val();current_max_filter=parseInt(current_max_filter,10);$(".filter-price-max").empty();for(i=0;i<7;i++){if(s_r==2){if(current_max_filter<1200){current_max_filter=current_max_filter+ 100;}else if(current_max_filter<2000){current_max_filter=current_max_filter+ 200;}else{current_max_filter=current_max_filter+ 5000;}}else{if(current_max_filter<600000){current_max_filter=current_max_filter+ 50000;}else if(current_max_filter<1500000){current_max_filter=current_max_filter+ 100000;}else{current_max_filter=current_max_filter+ 250000;}}
$(".filter-price-max").append('<li class=="xs-full-width"><a class="button button--dd xs-full-width xs-text-right" data-value="'+current_max_filter+'">$'+addCommas(current_max_filter)+'</a></li>');}
$(".filter-price-max").append('<li class="xs-full-width"><a class="button button--dd xs-full-width xs-text-right" data-value="0">Any Price</a></li>');$('.filter-price-max a').on('click',function(e){e.preventDefault();$(".filter-price-max  a").removeClass("selected");$(this).addClass('selected');$('#price-max').val($(this).data('value'));if($(this).data('value')==0){$('#price-max').val('');}
var price_desc=change_price_desc($('#price-min').val(),$(this).data('value'))
$("#price_desc").html(price_desc);$("#price-filter").removeClass('open');update_search_nav();process_home_search();});update_search_nav();}
function change_price_desc(min_price,max_price,show_blank){var price_desc='Any Price';if(show_blank){price_desc='';}
if(min_price>=950000){var display_min_price=min_price;display_min_price=display_min_price/100000;display_min_price=Math.round(display_min_price);display_min_price=display_min_price/10;display_min_price=display_min_price+'M';}else if(min_price>=10000){var display_min_price=min_price;display_min_price=display_min_price/1000;display_min_price=Math.round(display_min_price);display_min_price=display_min_price+'K';}else{display_min_price=min_price;}
if(max_price>=950000){var display_max_price=max_price;display_max_price=display_max_price/100000;display_max_price=Math.round(display_max_price);display_max_price=display_max_price/10;display_max_price=display_max_price+'M';}else if(max_price>=10000){var display_max_price=max_price;display_max_price=display_max_price/1000;display_max_price=Math.round(display_max_price);display_max_price=display_max_price+'K';}else{display_max_price=max_price;}
if(min_price>0&&!(max_price>0)){var price_desc='Over $'+ display_min_price;}else if(!(min_price>0)&&max_price>0){var price_desc='Under $'+ display_max_price;}else if(min_price>0&&max_price>0){var price_desc='$'+ display_min_price+' to $'+ display_max_price;}
return price_desc;}
function update_search_nav(){var c_total_search=0;var ptype_desc='Home Type';var c_ptype=0;var saved_search_string='';var saved_search_string_type=''
var m_filter_count=0;if(typeof pageAction!=='undefined'&&pageAction=='map'){search_url='/map_search.php?sarea='+ $("#sarea").val();}else{search_url='/index.php?sarea='+ $("#sarea").val();}
if($("#property-type-house").is(':checked')){ptype_desc='House';c_ptype=c_ptype+ 1;m_filter_count++;saved_search_string_type='House';search_url=search_url+'&ptype_house=1';}
if($("#property-type-condo").is(':checked')){ptype_desc='Condo';c_ptype=c_ptype+ 1;m_filter_count++;if(saved_search_string_type!=''){saved_search_string_type=saved_search_string_type+', Condo';}else{saved_search_string_type='Condo';}
search_url=search_url+'&ptype_condo=1';}
if($("#property-type-townhouse").is(':checked')){ptype_desc='Townhouse';c_ptype=c_ptype+1;m_filter_count++;if(saved_search_string_type!=''){saved_search_string_type=saved_search_string_type+', Townhouse';}else{saved_search_string_type='Townhouse';}
search_url=search_url+'&ptype_townhouse=1';}
if(c_ptype>1){ptype_desc='Home Type ('+ c_ptype+')';}
$("#ptype_desc").html(ptype_desc);var c_atts=0;if($("#min_baths").val()!=''&&$("#min_baths").val()!=0){c_atts=c_atts+1;m_filter_count++;search_url=search_url+'&min_baths='+$("#min_baths").val();}
if($("#min_sqft").val()!=''&&$("#min_sqft").val()!=0){c_atts=c_atts+1;m_filter_count++;search_url=search_url+'&min_sqft='+$("#min_sqft").val();}
if($("#days_on_zolo").val()!=''&&$("#days_on_zolo").val()!=0){c_atts=c_atts+1;m_filter_count++;search_url=search_url+'&days_on_zolo='+$("#days_on_zolo").val();}
if($("#has_photos").val()!=''&&$("#has_photos").val()!=0){c_atts=c_atts+1;m_filter_count++;search_url=search_url+'&has_photos='+$("#has_photos").val();}
if($("#attribute-terms").val()!=''&&$("#attribute-terms").val()!=0){c_atts=c_atts+1;m_filter_count++;search_url=search_url+'&attribute_terms='+$("#attribute-terms").val();}
var catts_desc='More';if(c_atts>0){catts_desc='More ('+ c_atts+')';}
$("#more_search_desc").html(catts_desc);if($("#sarea_hidden").val()!=''){saved_search_string=$("#sarea_hidden").val();}
if($("#sarea").val()!=''){saved_search_string=$("#sarea").val();}
saved_search_string=$.trim(saved_search_string);var min_beds_desc='0+ Bed';if($("#min_beds").val()>1){saved_search_string=saved_search_string+', '+$("#min_beds").val()+' beds';min_beds_desc=$("#min_beds").val()+'+ beds';m_filter_count++;search_url=search_url+'&min_beds='+$("#min_beds").val();}
if($("#min_beds").val()==1){saved_search_string=saved_search_string+', '+$("#min_beds").val()+' bed';min_beds_desc=$("#min_beds").val()+'+ bed';m_filter_count++;search_url=search_url+'&min_beds='+$("#min_beds").val();}
$("#min_bed_desc").html(min_beds_desc);if(saved_search_string_type!=''){saved_search_string=saved_search_string+', '+saved_search_string_type;}
var saved_search_string_price=change_price_desc($("#price-min").val(),$("#price-max").val(),true);if(saved_search_string_price!=''){saved_search_string=saved_search_string+', '+saved_search_string_price;}
$("#save-search-promo-content").html(saved_search_string);$("#save-search-promo-content-topnav").html(saved_search_string);$("#price_desc").html(change_price_desc($("#price-min").val(),$("#price-max").val()));if($("#price-max").val()>0){m_filter_count++;search_url=search_url+'&max_price='+$("#price-max").val();}
if($("#price-min").val()>0){m_filter_count++;search_url=search_url+'&min_price='+$("#price-min").val();}
$("#mobile_filer_count").data("count",m_filter_count);var status_desc='For Sale';if($("#s_r").val()>1){status_desc='For Rent';search_url=search_url+'&s_r='+ $("#s_r").val();}
$("#status_desc").html(status_desc);set_min_prices();}
function inputHasValue(elem){return $(elem).filter(function(){return $(this).val();}).length>0;}
function slugify(text){return text.toString().toLowerCase().replace(/\s+/g,'-').replace(/_/g,'-').replace(/[^\w\-]+/g,'').replace(/^-+/,'').replace(/-+$/,'');}
function set_search_url(data){var numPropertyTypesSelected=$('li.filter-property-type').find($('div.dropdown-menu')).find($('ul.list-unstyled')).find($('input.checkbox:checked')).length;var nonSEOFriendlyInputsAreEmpty=false;var locationOnlySearch=false;var urlFriendlyLocationSearch=false;var isSEOFriendly=false;if($('#min_baths').val()==0&&$('#min_sqft').val()==0&&$('#days_on_zolo').val()==0&&$('#has_photos').val()==0&&!inputHasValue('#attribute-terms')&&!inputHasValue('#price-max')&&!inputHasValue('#price-min')){nonSEOFriendlyInputsAreEmpty=true;}
if((nonSEOFriendlyInputsAreEmpty&&numPropertyTypesSelected==0&&$("#min_beds").val()==0)||isListingPage){locationOnlySearch=true;if(ZOLO.searchCity()!=''||ZOLO.searchNeighborhood()!=''){urlFriendlyLocationSearch=true;}}
if(ZOLO.searchCity()!=''||ZOLO.searchNeighborhood()!=''){urlFriendlyLocationSearch=true;}
if(nonSEOFriendlyInputsAreEmpty&&typeof pageAction!=='undefined'&&pageAction=='index'&&(urlFriendlyLocationSearch&&($("#min_beds").val()>=0&&numPropertyTypesSelected<=1))){isSEOFriendly=true;}else if(isListingPage&&urlFriendlyLocationSearch){isSEOFriendly=true;}
if(typeof pageAction!=='undefined'&&pageAction=='map'){search_url='/map_search.php?sarea='+$("#sarea").val();}else if(pageAction!=='undefined'&&(pageAction=='index'||isListingPage)&&isSEOFriendly){if(locationOnlySearch&&urlFriendlyLocationSearch){if(ZOLO.searchCity()!=''&&ZOLO.searchNeighborhood()!=''){search_url='/'+slugify(ZOLO.searchCity())+'-real-estate/'+slugify(ZOLO.searchNeighborhood());if($("#s_r").val()>1){search_url+='/for-rent';}}else if(ZOLO.searchCity()!=''){search_url='/'+slugify(ZOLO.searchCity())+'-real-estate';if($("#s_r").val()>1){search_url+='/for-rent';}}}else if(nonSEOFriendlyInputsAreEmpty&&$("#min_beds").val()>=0&&numPropertyTypesSelected<=1&&urlFriendlyLocationSearch){if(ZOLO.searchCity()!=''&&ZOLO.searchNeighborhood()!=''){search_url='/'+slugify(ZOLO.searchCity())+'-real-estate/'+slugify(ZOLO.searchNeighborhood())+'/';}else if(ZOLO.searchCity()!=''){search_url='/'+slugify(ZOLO.searchCity())+'-real-estate/';}
if($("#min_beds").val()>0){search_url+=$("#min_beds").val()+'-bedroom';if(numPropertyTypesSelected==1){search_url+='-';}}
if($("#property-type-house").is(':checked')&&!($("#property-type-townhouse").is(':checked'))&&!($("#property-type-condo").is(':checked'))){search_url+='houses';}else if($("#property-type-townhouse").is(':checked')&&!($("#property-type-house").is(':checked'))&&!($("#property-type-condo").is(':checked'))){search_url+='townhouses';}else if($("#property-type-condo").is(':checked')&&!($("#property-type-house").is(':checked'))&&!($("#property-type-townhouse").is(':checked'))){if($("#s_r").val()>1){search_url+='apartments-for-rent';}else{search_url+='condos';}}
if($("#s_r").val()>1&&!$("#property-type-condo").is(':checked')){search_url+='-for-rent';}}}else{search_url='/index.php?sarea='+$("#sarea").val();if(isListingPage){search_url='/index.php?sarea='+$("#mobile_sarea").val()+'&filter=1';}}
if(!isSEOFriendly&&!isListingPage){var has_filters=0;if($("#property-type-condo").is(':checked')){search_url=search_url+'&ptype_condo=1';has_filters=1;}
if($("#property-type-house").is(':checked')){search_url=search_url+'&ptype_house=1';has_filters=1;}
if($("#property-type-townhouse").is(':checked')){search_url=search_url+'&ptype_townhouse=1';has_filters=1;}
if($("#min_baths").val()!=''&&$("#min_baths").val()!=0){search_url=search_url+'&min_baths='+$("#min_baths").val();has_filters=1;}
if($("#min_sqft").val()!=''&&$("#min_sqft").val()!=0){search_url=search_url+'&min_sqft='+$("#min_sqft").val();has_filters=1;}
if($("#days_on_zolo").val()!=''&&$("#days_on_zolo").val()!=0){search_url=search_url+'&days_on_zolo='+$("#days_on_zolo").val();has_filters=1;}
if($("#has_photos").val()!=''&&$("#has_photos").val()!=0){search_url=search_url+'&has_photos='+$("#has_photos").val();has_filters=1;}
if($("#attribute-terms").val()!=''&&$("#attribute-terms").val()!=0){search_url=search_url+'&attribute_terms='+$("#attribute-terms").val();has_filters=1;}
if($("#min_beds").val()>0){search_url=search_url+'&min_beds='+$("#min_beds").val();has_filters=1;}
if($("#price-max").val()>0){search_url=search_url+'&max_price='+$("#price-max").val();has_filters=1;}
if($("#price-min").val()>0){search_url=search_url+'&min_price='+$("#price-min").val();has_filters=1;}
if($("#s_r").val()>1){search_url=search_url+'&s_r='+$("#s_r").val();}
search_url=search_url+'&filter=1';}
if($(window).width()>768){history.pushState(data,null,search_url);}else if($(window).width()<=768&&ZOLO.whichSearchDrawer=='location-only'){window.location=search_url;}else{return search_url;}}
window.addEventListener('popstate',function(e){var filteredData=e.state;if(filteredData!==null){update_search_nav();process_home_search(filteredData);}});if(typeof pageAction!=='undefined'&&pageAction=='index'||isListingPage){$("#home_search_top").submit(function(){update_search_nav();process_home_search();return false;});}
$('.js-button-filter').on('click',function(e){e.preventDefault();});$(".checkbox").change(function(){update_search_nav();process_home_search();});$("#price-min").change(function(){set_max_prices(parseInt($('#price-min').val()));var price_desc=change_price_desc($('#price-min').val(),$('#price-max').val())
$("#price_desc").html(price_desc);update_search_nav();process_home_search();});$("#price-max").change(function(){var price_desc=change_price_desc($('#price-min').val(),$('#price-max').val())
$("#price_desc").html(price_desc);update_search_nav();process_home_search();});$("#price-max").focus(function(){$(".filter-price-min").hide();$(".filter-price-max").show();});$("#price-min").focus(function(){$(".filter-price-max").hide();$(".filter-price-min").show();});$('.filter-bed-values a').on('click',function(e){e.preventDefault();$(".filter-bed-values a").removeClass("selected");$(this).addClass('selected');$('#min_beds').val($(this).data('value'));var min_beds_desc=$(this).data('value')+'+ beds';$("#min_bed_desc").html(min_beds_desc);update_search_nav();process_home_search();});$('.filter-status-values a').on('click',function(e){e.preventDefault();$(".filter-status-values a").removeClass("selected");$(this).addClass('selected');$('#s_r').val($(this).data('value'));var status_desc='For Sale';if($(this).data('value')==2){status_desc='For Rent';}
$("#status_desc").html(status_desc);$('#price-min').val('');$('#price-max').val('');update_search_nav();process_home_search();});$('.filter-price-min a').on('click',function(e){e.preventDefault();$(".filter-price-min  a").removeClass("selected");$(this).addClass('selected');$('#price-min').val($(this).data('value'));if($(this).data('value')==0){$('#price-min').val('');}
var this_min_price=$(this).data('value');var current_max_filter=this_min_price;set_max_prices(current_max_filter)
var price_desc=change_price_desc($(this).data('value'),$('#price-max').val())
$("#price_desc").html(price_desc);$(".filter-price-min").hide();$(".filter-price-max").show();update_search_nav();process_home_search();$("#price-filter").addClass('open');$("#price-max").focus();});$('.filter-price-max a').on('click',function(e){e.preventDefault();$(".filter-price-max  a").removeClass("selected");$(this).addClass('selected');$('#price-max').val($(this).data('value'));if($(this).data('value')==0){$('#price-max').val('');}
var price_desc=change_price_desc($('#price-min').val(),$(this).data('value'))
$("#price_desc").html(price_desc);$(".filter-price-min").show();$(".filter-price-max").hide();update_search_nav();process_home_search();});if($(window).width()<=768){$("#attribute-terms").change(function(){update_search_nav();process_home_search();});$(".filter-input .select").change(function(){update_search_nav();process_home_search();});}
$(document).ready(update_search_nav());$(document).ready(set_max_prices($("#price-max").val()));