var map="";var markers=new Array();var htmlMarkers=new Array();var viewportWidth=0;var maxNum=1;var num=0;var list=[];var listings_html="";var distance=6;var default_lat=49.2505;var default_lng=-123.1119;var min_lat=default_lat-distance/111;var min_lng=default_lng-distance/85;var max_lng=default_lng+distance/85;var max_lat=default_lat+distance/111;var markersClicked=sessionStorage.getItem("markersClicked");var focusedMarker="";var isListingPage=ZOLO.isListingPage();var area;if(!isListingPage){area=mapSearchInfo.sarea;}else{area=ZOLO.mapArea();}
function gallerySetup(){document.getElementById("home_search_top").addEventListener("submit",function(){sessionStorage.sarea="";});}
function restoreMapState(){var zoom=JSON.parse(sessionStorage.getItem("mapZoom"));var sarea_different=checkSearchArea(area);if(!sarea_different&&area!="my_location"){var center_lat_lng=getSessionCenter();if(center_lat_lng){map.setCenter(center_lat_lng);map.setZoom(zoom.num);}}}
function listingSetup(){}
function HTMLMarker(location){this.pos=location;}
function propertyModal(item,marker){marker.addEventListener("click",function(){var checkClicked=false;if(markersClicked){markersClicked.indexOf(item.propertyId)>=0;}
if(!checkClicked){if(!markersClicked){markersClicked="";}
markersClicked+=item.propertyId+",";this.childNodes[0].className+=" visited";sessionStorage.markersClicked=markersClicked;}
var boxText=document.createElement("div");boxText.innerHTML=item.body;var myOptions={content:boxText,disableAutoPan:false,maxWidth:0,alignBottom:false,pixelOffset:new google.maps.Size(-60,0),boxClass:"map-sum",closeBoxMargin:"0",closeBoxURL:"",infoBoxClearance:new google.maps.Size(1,1),isHidden:false,pane:"floatPane",enableEventPropagation:false};var ww=$(window).width;$('#listingModal').modal({keyboard:false})
$('#listingModal').show().html('<div class=\"progress progress-warning progress-striped active loading\"><div class=\"bar\" style=\"width: 100\%\"></div></div>');modalData={ID:item.propertyId,vw:screen.width,frommap:1,cpaddress:item.cpaddress,ds:1}
if(isListingPage){modalData.no_search=1;}
$.ajax({cache:true,type:'GET',url:tld+'mapmodel.php',data:modalData,success:function(data){$('#listingModal').show().html(data);}});if(item.ptype!='hearted'){this.childNodes[0].className+=" visited ";}
return false;});}
function saveMapState(){if(typeof(Storage)!=="undefined"&&(action=="map")){updateCenter(map.getCenter());updateZoom(map.getZoom());checkSearchArea(area);}else{}}
function updateCenter(center){if(typeof(Storage)!=="undefined"){try{if(center){sessionStorage.mapCenter='{"lat": '+ center.lat()+', "lng": '+ center.lng()+'}';}}catch(e){console.log(e);}}else{console.log("Sorry, your browser does not support web storage...");}}
function getSessionCenter(){var coords=JSON.parse(sessionStorage.getItem("mapCenter"));if(coords&&action=="map"){var center_lat_lng=new google.maps.LatLng(coords.lat,coords.lng);return center_lat_lng;}
return false;}
function updateZoom(zoomNum){if(typeof(Storage)!=="undefined"){try{sessionStorage.mapZoom='{"num": '+ zoomNum+'}';}catch(e){console.log(e);}}else{console.log("Sorry, your browser does not support web storage...");}}
function setSessionArea(current){try{sessionStorage.sarea=current;}catch(e){console.log(e);}}
function checkSearchArea(current){if(typeof(Storage)!=="undefined"){var previous=sessionStorage.getItem('sarea');var diff=false;if(current!==previous){diff=true;}
return diff;}else{console.log("Sorry, your browser does not support web storage...");return false;}}
function handleNoGeolocation(errorFlag){var default_latlng=new google.maps.LatLng(default_lat,default_lng);map.setCenter(default_latlng);map.setZoom(12);}
function typeControl(){$(".btn-map-type").toggle(function(){$(this).toggleClass("btn-active");changeMapType('HYBRID');},function(){$(this).toggleClass("btn-active");changeMapType('ROADMAP');});}
function changeMapType(mapTypeId){map.setMapTypeId(google.maps.MapTypeId[mapTypeId]);}
function clearOverlays(){for(var i=0;i<markers.length;i++){markers[i].setMap(null);}
markers=[];for(var i=0;i<htmlMarkers.length;i++){htmlMarkers[i].setMap(null);}
htmlMarkers=[];}
function zoomControl(map){google.maps.event.addDomListener(zoomout,'click',function(){reloadProperties();var currentZoomLevel=map.getZoom();if(currentZoomLevel!=0){map.setZoom(currentZoomLevel- 1);}});google.maps.event.addDomListener(zoomin,'click',function(){reloadProperties();var currentZoomLevel=map.getZoom();if(currentZoomLevel!=21){map.setZoom(currentZoomLevel+ 1);}});var no_match_bar=document.querySelector(".no-matches");if(no_match_bar){no_match_bar.addEventListener("click",function(){reloadProperties();var currentZoomLevel=map.getZoom();if(currentZoomLevel!=0){map.setZoom(currentZoomLevel- 1);}});}}
function showMarker(post_id){$('#listingModal').modal({keyboard:false})
$('#listingModal').show().html('<div class=\"progress progress-warning progress-striped active loading\"><div class=\"bar\" style=\"width: 100\%\"></div></div>');$.ajax({cache:true,type:'GET',url:tld+'mapmodel.php',data:'ID='+ post_id,success:function(data){$('#listingModal').show().html(data);}});return false;}
function addPropertyMarker(map,location,title){var propertyMarker=new google.maps.MarkerImage("/img/map-pin-main-accent.png");propertyMarker.size=new google.maps.Size(80,380);propertyMarker.origin=new google.maps.Point(0,0);propertyMarker.anchor=new google.maps.Point(40,40);new google.maps.Marker({position:location,map:map,title:title,zIndex:1e6,clickable:false,icon:propertyMarker})}
function addMarker(map,item,location,i){var marker_icon='';var marker_icon_2='';var marker_icon_3='';switch(item.ptype){case'hearted':marker_icon='marker-heart.png';marker_icon_2='marker-heart.png';marker_icon_3='marker-heart.png';break;case'APT':case'APTU':case'2':case'W':case'C':case'3':case'E':case'Apartment':case'Apartment/Condo':case'Apartment High Rise':case'Lowrise Apartment':marker_icon='map-pins.png';marker_icon_2='map-pins-hover.png';marker_icon_3='map-pins-visited.png';break;default:marker_icon='map-pins.png';marker_icon_2='map-pins-hover.png';marker_icon_3='map-pins-visited.png';break;}
if(item.cpaddress>1){marker_icon='map-pins-plus.png';marker_icon_2='map-pins-plus-hover.png';marker_icon_3='map-pins-plus-visited.png';}
var icon_1=new google.maps.MarkerImage(tld+'images/'+marker_icon);icon_1.size=new google.maps.Size(18,18);icon_1.scaledSize=new google.maps.Size(18,18);icon_1.origin=new google.maps.Point(0,0);icon_1.anchor=new google.maps.Point(9,9);var icon_2=new google.maps.MarkerImage(tld+'images/'+marker_icon_2);icon_2.size=new google.maps.Size(18,18);icon_2.scaledSize=new google.maps.Size(18,18);icon_2.origin=new google.maps.Point(0,0);icon_2.anchor=new google.maps.Point(9,9);var icon_3=new google.maps.MarkerImage(tld+'images/'+marker_icon_3);icon_3.size=new google.maps.Size(18,18);icon_3.scaledSize=new google.maps.Size(18,18);icon_3.origin=new google.maps.Point(0,0);icon_3.anchor=new google.maps.Point(9,9);var checkClicked=false;if(markersClicked){checkClicked=markersClicked.indexOf(item.propertyId)>=0;}
if(map.getZoom()>14){HTMLMarker.prototype=new google.maps.OverlayView();HTMLMarker.prototype.onRemove=function(){this.div.parentNode.removeChild(this.div);this.div=null;}
HTMLMarker.prototype.onAdd=function(){var div=document.createElement('DIV');div.style.position='absolute';div.className="htmlMarker";div.innerHTML=item.list_price;div.style.cursor="pointer";if(item.ptype=='hearted'){div.childNodes[0].className+=" favorited ";}else if(checkClicked){div.childNodes[0].className+=" visited ";}
var panes=this.getPanes();panes.overlayImage.appendChild(div);propertyModal(item,div);this.div=div;}
HTMLMarker.prototype.draw=function(){var overlayProjection=this.getProjection();var position=overlayProjection.fromLatLngToDivPixel(this.pos);var panes=this.getPanes();this.div.style.left=position.x-31+'px';this.div.style.top=position.y-28+'px';}
var htmlMarker=new HTMLMarker(location);htmlMarker.setMap(map);htmlMarkers.push(htmlMarker);}else{if(htmlMarkers.length>0){clearOverlays();}
var icon_url=icon_1;if(checkClicked){icon_url=icon_3;}
var marker=new google.maps.Marker({map:map,position:location,icon:icon_url,zIndex:1});marker.cpaddress=item.cpaddress;marker.hearted=item.ptype=='hearted'?true:false;if(sessionStorage.focusedMarker&&sessionStorage.focusedMarker==item.propertyId){marker.setIcon(icon_2);focusedMarker=marker;}
if(item.ptype=='hearted'){marker.setZIndex(google.maps.Marker.MAX_ZINDEX+ 200);}
var myLPOptions={content:item.list_price,boxClass:"map-label",boxStyle:{width:"60px"},disableAutoPan:true,pixelOffset:new google.maps.Size(-30,-2),closeBoxURL:"",isHidden:false,pane:"mapPane",enableEventPropagation:true};markers.push(marker);if(item.ptype=='tpid'){infowindow.open(map,marker);infowindow.setContent(item.body);infowindow.setOptions({disableAutoPan:true});}
new google.maps.event.addListener(marker,"click",function(){if(focusedMarker!=""){if(focusedMarker.cpaddress>1){previouslyFocusedIconPath='map-pins-plus-visited.png';}else if(focusedMarker.hearted){previouslyFocusedIconPath='marker-heart.png';}else{previouslyFocusedIconPath='map-pins-visited.png'}
previouslyFocusedMarker=new google.maps.MarkerImage(tld+'images/'+previouslyFocusedIconPath);previouslyFocusedMarker.size=new google.maps.Size(18,18);previouslyFocusedMarker.scaledSize=new google.maps.Size(18,18);previouslyFocusedMarker.origin=new google.maps.Point(0,0);previouslyFocusedMarker.anchor=new google.maps.Point(9,9);focusedMarker.setIcon(previouslyFocusedMarker);}
focusedMarker=this;sessionStorage.focusedMarker=item.propertyId;this.setIcon(icon_2);var checkClicked=false;if(markersClicked){checkClicked=markersClicked.indexOf(item.propertyId)>=0;}
if(!checkClicked){if(!markersClicked){markersClicked="";}
markersClicked+=item.propertyId+",";sessionStorage.markersClicked=markersClicked;this.setIcon(icon_3);}
var boxText=document.createElement("div");boxText.innerHTML=item.body;var myOptions={content:boxText,disableAutoPan:false,maxWidth:0,alignBottom:false,pixelOffset:new google.maps.Size(-60,0),zIndex:null,boxClass:"map-sum",closeBoxMargin:"0",closeBoxURL:"",infoBoxClearance:new google.maps.Size(1,1),isHidden:false,pane:"floatPane",enableEventPropagation:false};var ww=$(window).width;$('#listingModal').modal({keyboard:false})
$('#listingModal').show().html('<div class=\"progress progress-warning progress-striped active loading\"><div class=\"bar\" style=\"width: 100\%\"></div></div>');modalData={ID:item.propertyId,vw:screen.width,frommap:1,cpaddress:item.cpaddress,ds:1}
if(isListingPage){modalData.no_search=1;}
$.ajax({cache:true,type:'GET',url:tld+'mapmodel.php',data:modalData,success:function(data){$('#listingModal').show().html(data);}});if(item.ptype!='hearted'){marker.setIcon(icon_2)}
return false;});var that;var markerHoverOn=function(){var that=this;this.setIcon(icon_2);this.setOptions({zIndex:1e6+ 1});};var markerHoverOff=function(){var checkClicked=false;if(markersClicked){checkClicked=markersClicked.indexOf(item.propertyId)>=0;}
if(!checkClicked){this.setIcon(icon_1);}else if(focusedMarker==this){this.setIcon(icon_2);}else{this.setIcon(icon_3);}
this.setOptions({zIndex:1});};google.maps.event.addListener(marker,"mouseover",markerHoverOn);google.maps.event.addListener(marker,"mouseout",markerHoverOff);}
latLngs.push(location);i++;}
function get_tile(id){$.ajax({cache:true,type:'GET',url:tld+'listing_tile_ajax.php',data:'id='+id,dataType:'html','success':function(data){$('.listings-wrapper').append(data);}});}
function get_map_data(data){var no_match_msg=document.querySelector('.no-matches');if(no_match_msg){$('.listings-wrapper').html('');$('.listings-container').addClass("loading");if(data.length==0){if($('.listings-wrapper').find('.no-prop').length==0){no_match_msg.classList.remove('hide');}}else{no_match_msg.classList.add('hide');$('.no-prop').remove();}}
list=[];listing_html="";latLngs=[];var total_tiles=0;var max_tiles=24;clearOverlays();$.each(data,function(index,value){var new_lat=value.lat;var new_lng=value.lng;var sqft_class='';var latlng=new google.maps.LatLng(parseFloat(new_lat),parseFloat(new_lng));if(value.sqft_range!=''){var living_area=value.sqft_range;}else{var living_area='-';}
if(value.show_basic<1){var bdy='<div><strong><a href="'+value.purl+'">Sign Up to See</a></strong>  - bd - ba, - ft<sup>2</sup></div>';}else{if(value.name_on_top=='1'){var bdy='<div class="map-sum-brokerage">'+value.agent_name+'</div><div><strong><a href="'+value.purl+'">$'+value.list_price+'</a></strong> '+value.bedrooms+'bd '+value.bathrooms+'ba</div>';}else{var bdy='<div><strong><a href="'+value.purl+'">$'+value.list_price+'</a></strong> '+value.bedrooms+'bd '+value.bathrooms+'ba</div><div class="map-sum-brokerage">'+value.agent_name+'</div>';}}
bdy='';var list_price;if(value.cpaddress>1){list_price='<div class="map-label-sub">'+value.cpaddress+' units</div>';}else{list_price='<div class="map-label-sub">$'+value.lpk+'</div>';}
var item={'propertyId':value.id,'location':value.city,'ptype':value.type,'body':bdy,'list_price':list_price,'cpaddress':value.cpaddress,};list.push(item);if(action=="map"&&viewportWidth>=1024){if(total_tiles<max_tiles){if(viewportWidth>600){get_tile(value.id);}
total_tiles++;if(value.board_id=='REB4'){var terms='This representation is based in whole or in part on data generated by the Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Real Estate Board of Greater Vancouver which assumes no responsibility for its accuracy.';var this_city=value.url_city;if(this_city.toLowerCase().indexOf("calgary")>0){var terms='The listing data is provided under copyright by the Calgary Real Estate Board. The data is deemed reliable but is not guaranteed accurate by the Calgary Real Estate Board or Zolo. Zolo Realty (Alberta) Inc. 125 Hidden Cove Calgary, AB';}else if(this_city.toLowerCase().indexOf("edmonton")>0){var terms='The listing data is provided under copyright by the Edmonton Real Estate Board. The data is deemed reliable but is not guaranteed accurate by the Edmonton Real Estate Board or Zolo. Zolo Realty (Alberta) Inc. 125 Hidden Cove Calgary, AB';}
$('.map-disclaimer').html(terms);}}}
addMarker(map,item,latlng,i);});if(listing_html!=''){document.querySelector('.listings-wrapper').innerHTML=listing_html;}
document.getElementById('map-loading').classList.add("map-toggle");var listings=document.querySelector('.listings-container');if(listings){setTimeout(function(){document.querySelector('.listings-container').classList.remove("loading");},800);}}
function get_map(url_params,main_url){$.ajax({type:"POST",url:main_url,data:url_params,dataType:'json',success:function(data){get_map_data(data);},});}
function reloadProperties(){saveMapState();viewportWidth=$(window).width();var search_params={};search_params["vw"]=viewportWidth;var url_params='';$('#map-loading').removeClass("map-toggle");$('.listings-container').addClass("loading");search_params["viewport"]=map.getBounds(),y=0;if(search_params["viewport"]){search_params["ne"]=search_params["viewport"].getNorthEast();search_params["sw"]=search_params["viewport"].getSouthWest();if(isListingPage){search_params["all_prop"]=1;search_params["cpid"]=ZOLO.propertyId();}else{search_params["mnp"]=document.getElementById('price-min').value;search_params["mxp"]=document.getElementById('price-max').value;search_params["b"]=document.getElementById('min_beds').value;search_params["baths"]=document.getElementById('min_baths').value;search_params["mnsqft"]=document.getElementById('min_sqft').value;if(document.getElementById("property-type-condo").checked==true){search_params["ptc"]=1;}else{search_params["ptc"]=0;}
if(document.getElementById("property-type-house").checked==true){search_params["pth"]=1;}else{search_params["pth"]=0;}
if(document.getElementById("property-type-townhouse").checked==true){search_params["ptt"]=1;}else{search_params["ptt"]=0;}
search_params["doz"]=document.getElementById('days_on_zolo').value;search_params["hp"]=document.getElementById('has_photos').value;search_params["at"]=document.getElementById('attribute-terms').value;search_params["s_r"]=document.querySelector('input[name="s_r"]').value;search_params["mnp"]=(search_params["mnp"]=='')?0:search_params["mnp"];search_params["mxp"]=(search_params["mxp"]=='')?0:search_params["mxp"];search_params["b"]=(search_params["b"]=='')?0:search_params["b"];}
var counter=0;for(var key in search_params){if(counter>0){url_params+="&";}
url_params+=key+"="+ search_params[key];counter++;}
if(!isListingPage){url_params+='&tpid='+mapSearchInfo.tpid;}
var main_url=tld+'gallery_map_json.php';get_map(url_params,main_url);}}
function mapChange(){var event=new CustomEvent("mapChange",{detail:{},bubbles:true,cancelable:true});document.getElementById("ap_map_canvas").dispatchEvent(event);}
function initialize(){var CustomStyles=[{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":"-100"},{"color":"#444444"}]},{"featureType":"landscape.man_made","elementType":"all","stylers":[{"visibility":"on"}]},{"featureType":"landscape.man_made","elementType":"geometry","stylers":[{"saturation":"-100"},{"lightness":"70"},{"gamma":"0.80"}]},{"featureType":"landscape.natural","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"poi.park","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#ebefeb"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45},{"visibility":"simplified"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels.icon","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#46bcec"}]}];var CustomStylesDark=[{"featureType":"all","elementType":"labels.text.fill","stylers":[{"color":"#FFFFFF"}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"color":"#555555"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"simplified"},{"color":"#FFFFFF"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels.icon","stylers":[{"visibility":"on"}]},];var myOptions={scrollwheel:false,disableDefaultUI:true,zoom:isListingPage?16:12,mapTypeControlOptions:{mapTypeIds:[google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.HYBRID]},mapTypeControl:false,panControl:false,zoomControl:false,scaleControl:false,streetViewControl:false,backgroundColor:'#fafafa',draggable:true,styles:CustomStyles,gestureHandling:'greedy'};var mapId='ap_map_canvas';map=new google.maps.Map(document.getElementById(mapId),myOptions);zoomControl(map);typeControl();if(area==""){area="my_location";}
if(area=="my_location"&&navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){var pos=new google.maps.LatLng(position.coords.latitude,position.coords.longitude);map.setCenter(pos);map.setZoom(16);reloadProperties();},function(){handleNoGeolocation(true);reloadProperties();});}else{var geocoder=new google.maps.Geocoder();var geoOptions={address:area,region:"CA"};geocoder.geocode(geoOptions,function(results,status){var session_center=getSessionCenter();var is_area_new=checkSearchArea(area);if(!is_area_new&&!isListingPage){restoreMapState();}else if(status==google.maps.GeocoderStatus.OK){if(!isListingPage){setSessionArea(area);}
var location_center=results[0].geometry.location;map.setCenter(location_center);if(isListingPage){addPropertyMarker(map,location_center,area);}}else{if(mapSearchInfo.min_lat!=""){min_lat=mapSearchInfo.min_lat;}
if(mapSearchInfo.min_lng!=""){min_lng=mapSearchInfo.min_lng;}
if(mapSearchInfo.max_lat!=""){max_lat=mapSearchInfo.max_lat;}
if(mapSearchInfo.max_lng!=""){max_lng=mapSearchInfo.max_lng;}
var southwest=new google.maps.LatLng(min_lat,min_lng);var northeast=new google.maps.LatLng(max_lat,max_lng);map.fitBounds(new google.maps.LatLngBounds(southwest,northeast));}});}
google.maps.event.addListener(map,'maptypeid_changed',function(){if(this.getMapTypeId()==google.maps.MapTypeId.HYBRID){this.setOptions({styles:CustomStylesDark});}
else if(this.getMapTypeId()==google.maps.MapTypeId.ROADMAP){this.setOptions({styles:CustomStyles});}});google.maps.event.trigger(map,'maptypeid_changed');google.maps.event.addListener(map,'idle',mapChange);$(".wrapper").on("click","[data-favorite]",mapChange);document.getElementById("ap_map_canvas").addEventListener("mapChange",reloadProperties,false);if(action=="map"){gallerySetup();}}
function load_script(){var script=document.createElement("script");script.type="text/javascript";script.async="";var gm_key_string="&key="+gm_key;script.src="https://maps.googleapis.com/maps/api/js?callback=initialize";script.src=script.src+ gm_key_string;document.body.appendChild(script);}
window.load=load_script();